version: '3'
services:
  livebook:
    image: ghcr.io/livebook-dev/livebook
    ports:
      - 8090:8090
      - 8091:8091
    volumes: 
      - /docker-volumes/livebook-dev:/data 
    environment:
      - LIVEBOOK_PORT=8090
      - LIVEBOOK_IFRAME_PORT=8091
      - LIVEBOOK_PASSWORD=yjinheon2345

